apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 9090
    resources:
      limits:
        cpu: "200m"
        memory: "1Gi"
